### PR TITLE
Laura/59 add missing put options head request docs to the http runtime api

### PR DESCRIPTION
**Pull request by LauraLangdon**
Added missing put, options, and head http request methods to close Issue #59.

### CODE REVIEW

**Comment by flaki** [comment]
@LauraLangdon could you make sure the `.idea` folder is not in the PR? Either just make sure that it does not get committed, or I don't mind if you add it to `.gitignore` as part of the PR (it's not a big deal and not worth a separate PR)

**Comment by LauraLangdon** [comment]
> @LauraLangdon could you make sure the `.idea` folder is not in the PR? Either just make sure that it does not get committed, or I don't mind if you add it to `.gitignore` as part of the PR (it's not a big deal and not worth a separate PR)

Done!

**Comment by flaki** [comment]
@LauraLangdon could you link to the Reactr APIs on which you based the new docs information or tell a bit more about this PR and your research/context, to make review easier? (This is so I wouldn't have to go through and double-check every single API)

**Comment by LauraLangdon** [comment]
> @LauraLangdon could you link to the Reactr APIs on which you based the new docs information or tell a bit more about this PR and your research/context, to make review easier? (This is so I wouldn't have to go through and double-check every single API)

Sure, I used the following and @ramonh helped me figure out the pattern matching with the already-documented methods:

[JS/TS](https://github.com/suborbital/reactr/blob/main/api/typescript/src/modules/http.ts)
[Rust](https://github.com/suborbital/reactr/blob/main/api/rust/core/src/http/method.rs)
[TinyGo](https://github.com/suborbital/reactr/blob/main/api/tinygo/runnable/http/http.go)
[Swift](https://github.com/suborbital/reactr/blob/main/api/swift/Sources/suborbital/lib.swift)

**Review by flaki — COMMENTED** [review]
[Looks good](https://suborbital.github.io/docs/laura/59-add-missing-put-options-head-request-docs-to-the-http-runtime-api/atmo/runnable-api/http-client/) to me!

**Review by flaki — APPROVED** [review]

**Pull request merged**
