### PR TITLE
Preparing the docs for pre-release

### PR DESCRIPTION
**Pull request by flaki**
This one includes a bunch of tweaks to the startpage, sidebar, CSS and content. This PR is WIPish, the sidebar still needs tweaking and there is still plenty of content that needs updating or writing (e.g. #6 ).

The [sidebar](https://docusaurus.io/docs/sidebar/items) is pretty flexible, `category` items can be forced open (`collapsed: false`), or collapsing can be turned off completely (`collapsible: false`). Furthermore, category labels themselves could, and *should* be pointing to a document themselves via [category links](https://docusaurus.io/docs/sidebar/items#category-link). This can further help reduce the complexity of the sidebar.

Through these features I made several tweaks to the sidebar already and adjusted content where needed.

I also adjusted the layout and formatting of the startpage to reduce the white space and bring content closer to/above the fold.

Changes can be previewed at: https://suborbital.github.io/docs/

### CODE REVIEW

**Comment by cohix** [comment]
@flaki this is looking GREAT!

The main change I'd like to see is on the homepage:

- I've decided not to use the SCN logo, and instead let's just pretend 'Suborbital' and 'Suborbital Compute' are one in the same in this context. Let's have the Suborbital logo first-row-left (instead of the text header), and have the 'get started' link bring you to the Compute docs. Let's change the short blurb to instead be about Compute (extend and customize SaaS, etc)

- first-row-right let's have a 'WebAssembly' heading, a quick sentence about Wasm, and the link to 'What is WebAssembly?'

- In the second row let's put Atmo and then Sat. I don't have a logo for Sat yet, but let's put it beside Atmo in the second row. Please add an empty category for Sat in the sidebar (I'll be filling in the content soon)

- Third row is great!

Well done on this, it's starting to really come together.

**Comment by cohix** [comment]
Also, on the main 'Compute' page, the 'give it a try' link still goes to the Typeform... let's replace that link with `https://suborbital.network`

**Comment by cohix** [comment]
Oh and one last thing, a teeny nit, I like to have the building blocks ordered RVG (Reactr, Vektor, Grav)... it's mostly just a habit, but also roughly the order in which I think people should care about them :)

**Comment by flaki** [comment]
@cohix the above should all be addressed in the last update. There's plenty to clean up and tweak on the docs themselves (esp. the taxonomy), not to mention going through the docs and ensuring that we use Docusaurus' features [to their full extent](https://suborbital.github.io/docs/atmo/getstarted/prerequisites) but it's shaping up real nice I'd say.

PS: I made a quick placeholder icon for Sat so it doesn't mess with the overall looks of the page :)

**Comment by flaki** [comment]
>     * In the second row let's put Atmo and then Sat. I don't have a logo for Sat yet, but let's put it beside Atmo in the second row. Please add an empty category for Sat in the sidebar (I'll be filling in the content soon)

Yeah! I'm currently re-thinking the Atmo sidebar/content structure a bit to make it easier to grok but not be too overwhelming, also need to dig into Docusaurus a bit more (e.g. the parent category labels are not showing up anywhere and that kinda makes it less straightforward what's going on, will need to do a bit of research on this, see how it's done on other Docusaurus sites).

But other than that, I'd be happy to pair if you don't have anything on paper yet about Sat to kickstart those docs, or if you do just drop them into e.g. Notion and we can work on that async. Either case, if you have any ideas about how you want to structure it feel free to drop them in a Notion page and send it over. :)

**Comment by flaki** [comment]
These commits put the docs infra in a good place. There still are various pending tasks of tweaks, refactoring and additional content needs that could be addressed separately, I'm merging this PR as the new baseline.

**Pull request merged**
