### PR TITLE
Add `wat` format support

### LINKED ISSUE #139: Document `wat` support in subo
Since the [latest subo release](https://github.com/suborbital/subo/releases/tag/v0.5.0) adds support for `wat`, [let's list it](https://docs.suborbital.dev/reactr/language-support#support-status)!

### PR DESCRIPTION
**Pull request by ramonh**
Closes #139 

I hope that listing this as "Stable" is accurate!

@ospencer could you please confirm? Thank you!

### CODE REVIEW

**Review by flaki — APPROVED** [review]
LGTM!

@ramonh do you think it would make sense to footnote this and mention that `.wat` support is available since [`subo v0.5`](https://github.com/suborbital/subo/releases/tag/v0.5.0)?

**Comment by ramonh** [comment]
Thanks for the feedback @flaki. I wonder if this might be not suited better for a changelog of sorts?

**Comment by ospencer** [comment]
Stable is fine :)

**Comment by ramonh** [comment]
> Stable is fine :)

Thanks for confirming!

**Pull request merged**
