### PR TITLE
Atmo docs revamp

### PR DESCRIPTION
**Pull request by flaki**
- Fixed homepage icons and added new Sat icon
- Moving to Docusaurus built-ins
- Further improved sidebar
- Added first take on Sat docs
- Revamped & slightly reorganized Atmo docs

Preview: https://suborbital.github.io/docs/

### CODE REVIEW

**Comment by cohix** [comment]
This is awesome! A few notes:
- Should we remove the logo from the top bar on the homepage? Seems odd to have two
- IMO the ordering for the Runnable API section should be: Example runnable, handling requests, modifying responses, logging, http, graphql, authentication, cache, files
- The warning about Subo on Windows is a bit too harsh, could we downgrade from a yellow warning to an 'info', and change the wording to say "not officially supported" rather than "not compatible" ? 
And could we move the Using SQL databases page down to the Runnable API section, and add some more languages? It's supported in more than just Rust now 🙂

**Comment by flaki** [comment]
I filed #28 for a follow-up for the logo issue.

Good point on the Runnable API, I reorganized it and moved the example runnable into the intro page. I fixed the outstanding language-specific APIs there too. I also have #27 for making this easier (potentially automated?) in the future, because it's annoying to maintain this manually, and error-prone (same as why we want `wit-bindgen`).

I adjusted the Windows support note, the SQL stuff now lives in the Runnable API now too (this was something I was wondering about myself before), I'll look into AS/Swift support and can add that note later as well.

**Comment by cohix** [comment]
This is wonderful! There are only two small tweaks I'd like to make before merging this PR:

- I've changed Atmo's description to be 'Application framework for cloud native WebAssembly', so let's try using that on the homepage here as well

- I've changed Sat's description to 'Tiny & fast WebAssembly edge compute server` so let's use that

I've also filed https://github.com/suborbital/docs/issues/30 with all of my nitpicks and tweaks, but this PR can proceed without those :)

**Comment by flaki** [comment]
Love the new taglines! Adjusted them accordingly, and will merge this now.

**Pull request merged**
