### PR TITLE
Integrate fathom analytics

### LINKED ISSUE #200: Integrate Fathom analytics

### PR DESCRIPTION
**Pull request by hola-soy-milk**
Closes #200

### CODE REVIEW

**Comment by callahad** [comment]
Would've expected the package-lock.json to get updated, too?

**Comment by hola-soy-milk** [comment]
Hold up, good catch. I just noticed we have both a package-lock and a yarn-lock.

**Comment by callahad** [comment]
haha, awesome. Otherwise LGTM

**Comment by hola-soy-milk** [comment]
Ok, so I thought we had to install via yarn, but it turns out npm install did the trick.

Do we maybe want to see about eliminating one of the two? Having one single source of truth when it comes to dependencies might be a best bet here.

I get nervous about having both a yarn.lock and a package-lock

**Comment by hola-soy-milk** [comment]
For reference: The[ website repo has both checked in but refers to yarn](https://github.com/suborbital/website) in the README

**Comment by callahad** [comment]
Yeah. Website should canonically be Yarn. Docs should canonically be NPM.

After merging this PR we should drop the mention of Yarn in the Docs README (and in the docs themselves, probably. folks using yarn know how to use yarn).

We should probably switch the website over to npm from Yarn, too, though that'll also require updating the vercel config (ideally via a PR to the suborbital/fleet repo)

**Comment by hola-soy-milk** [comment]
I'm +1 on this. Just integrating fathom into Network which uses npm and the consistency advocate in me is eager.

In the meantime, is this good to go?

**Review by callahad — APPROVED** [review]
lgtm

**Pull request merged**
